# Generated by Django 3.1.13 on 2021-11-09 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='ask_type',
            field=models.CharField(choices=[('PUBLIC', 'public'), ('LIMITED', 'limited')], default='PUBLIC', max_length=7),
        ),
    ]
