# Generated by Django 3.1.13 on 2021-11-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_auto_20211109_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='ask_type',
            field=models.CharField(choices=[('public', 'Public'), ('limited', 'Limited')], default='public', max_length=7),
        ),
    ]
