# Generated by Django 3.1.13 on 2021-11-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_auto_20211118_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='ask_type',
            field=models.CharField(choices=[('public', 'public'), ('limited', 'limited')], default='public', max_length=7),
        ),
    ]
