# Generated by Django 4.2.8 on 2024-09-29 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answervote',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='answervote',
            name='voter',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='commentvote',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='commentvote',
            name='voter',
        ),
        migrations.RemoveField(
            model_name='education',
            name='user',
        ),
        migrations.RemoveField(
            model_name='employment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='followee',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='location',
            name='user',
        ),
        migrations.RemoveField(
            model_name='question',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='token',
            name='user',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='AnswerVote',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='CommentVote',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Employment',
        ),
        migrations.DeleteModel(
            name='EndUser',
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Token',
        ),
    ]
